In [34]:
import tensorflow as tf
import numpy as np

In [35]:
input_1 = tf.keras.layers.Input(shape=(3,))

Initialize vectors
https://towardsdatascience.com/how-to-use-dataset-in-tensorflow-c758ef9e4428

In [36]:
y = tf.math.square(input_1)

x= np.random.normal(0,1, (100, 3))
y_true = np.random.randint(0, 2, (100,1))
y_pred = np.random.random(size=(100,1))

loss = tf.keras.losses.mean_squared_error(y_true, y_pred)


In [42]:
dataset = tf.data.Dataset.from_tensor_slices((x,y_true)) 


In [44]:
for i in dataset:
    print(i)

(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([-1.44824861,  1.60796533,  1.61293318])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>)
(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([-0.10981098, -1.03858279, -0.73854841])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0])>)
(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([-0.2156173 , -1.09798854,  0.30278789])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>)
(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([-0.31575191,  1.20247733, -0.97247834])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([0])>)
(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([0.35937466, 1.29827107, 1.77654828])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>)
(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([-0.23827392, -1.14523488, -0.3182119 ])>, <tf.Tensor: shape=(1,), dtype=int64, numpy=array([1])>)
(<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 0.30044406,  0.49190634, -0.99649511])>, <t

In [53]:
model = tf.keras.models.Sequential(
    [
        tf.keras.layers.Dense(64, activation='relu', input_shape=(3,)),
        tf.keras.layers.Dense(64, activation='relu'),
        tf.keras.layers.Dense(1)
    ]
)
model.compile(optimizer='adam', loss='binary_crossentropy')
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_6 (Dense)             (None, 64)                256       
                                                                 
 dense_7 (Dense)             (None, 64)                4160      
                                                                 
 dense_8 (Dense)             (None, 1)                 65        
                                                                 
Total params: 4,481
Trainable params: 4,481
Non-trainable params: 0
_________________________________________________________________


In [57]:
model.fit(x,y_true,epochs=10,batch_size=10)

Epoch 1/10
10/10 [==============================] - 3s 19ms/step - loss: 3.8988
Epoch 2/10
10/10 [==============================] - 0s 5ms/step - loss: 0.8691
Epoch 3/10
10/10 [==============================] - 0s 7ms/step - loss: 0.7926
Epoch 4/10
10/10 [==============================] - 0s 9ms/step - loss: 0.7490
Epoch 5/10
10/10 [==============================] - 0s 4ms/step - loss: 0.7115
Epoch 6/10
10/10 [==============================] - 0s 4ms/step - loss: 0.7024
Epoch 7/10
10/10 [==============================] - 0s 5ms/step - loss: 0.6987
Epoch 8/10
10/10 [==============================] - 0s 5ms/step - loss: 0.6885
Epoch 9/10
10/10 [==============================] - 0s 5ms/step - loss: 0.6801
Epoch 10/10
10/10 [==============================] - 0s 8ms/step - loss: 0.6773
